{"id":"1.37.0","benchmarks":{"crates.io":{"Err":"ErrorMessage { msg: \"expected success, got exit code: 101\\n\\nstderr=error: process didn\\'t exit successfully: `/home/alex/code/rustc-perf/target/release/rustc-fake -vV` (exit code: 101)\\n--- stderr\\nthread \\'main\\' panicked at \\'failed to exec: No such file or directory (os error 2)\\', collector/src/bin/rustc-fake.rs:239:5\\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.\\n\\n\\n\\n stdout=\" }\n\nstack backtrace:\n   0: failure::backtrace::internal::InternalBacktrace::new::h283f8a35e18b39ba (0x555e8a3293c8)\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/internal.rs:44\n   1: failure::backtrace::Backtrace::new::h5621ac89965a2646 (0x555e8a329580)\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/mod.rs:111\n      <failure::backtrace::Backtrace as core::default::Default>::default::h8dabef315f83383d\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/mod.rs:125\n   2: <failure::error::error_impl::ErrorImpl as core::convert::From<F>>::from::heb5b6ca482359042 (0x555e8a2b1b93)\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error/error_impl.rs:19\n      <failure::error::Error as core::convert::From<F>>::from::hfc86b78db702192c\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error/mod.rs:36\n      failure::error_message::err_msg::h461cd386e782dee1\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error_message.rs:12\n      collector::command_output::hc1885b57ce0596d9\n             at collector/src/lib.rs:658\n   3: collector::execute::CargoProcess::run_rustc::h065da9d19ac8b57b (0x555e89f1112b)\n             at collector/src/bin/rustc-perf-collector/execute.rs:230\n   4: collector::execute::Benchmark::measure::haf66a21e925b39f7 (0x555e89f19832)\n             at collector/src/bin/rustc-perf-collector/execute.rs:765\n   5: collector::bench_commit::h4d92175941328511 (0x555e89f04ef3)\n             at collector/src/bin/rustc-perf-collector/main.rs:306\n   6: collector::bench_published::hd09f56af8a9672f1 (0x555e89f0c530)\n             at collector/src/bin/rustc-perf-collector/main.rs:227\n      collector::main_result::h6b0f033b291eba88\n             at collector/src/bin/rustc-perf-collector/main.rs:537\n   7: collector::main::h6fdc93a16be00aad (0x555e89f056ef)\n             at collector/src/bin/rustc-perf-collector/main.rs:382\n   8: std::rt::lang_start::{{closure}}::h80c0acaed3088f8e (0x555e89edb5c3)\n             at /rustc/890881f8f4c77e8670d4b32104c0325fcfefc90f/src/libstd/rt.rs:64\n   9: std::rt::lang_start_internal::{{closure}}::h206ab7e4498aa1c0 (0x555e8a354b53)\n             at src/libstd/rt.rs:49\n      std::panicking::try::do_call::h89a9b41ab5b49bd7\n             at src/libstd/panicking.rs:296\n  10: __rust_maybe_catch_panic (0x555e8a35f08a)\n             at src/libpanic_unwind/lib.rs:82\n  11: std::panicking::try::h1a76c542b7a68f0e (0x555e8a35571d)\n             at src/libstd/panicking.rs:275\n      std::panic::catch_unwind::hbf51b086a93263a6\n             at src/libstd/panic.rs:394\n      std::rt::lang_start_internal::hdbf5055a9a60353b\n             at src/libstd/rt.rs:48\n  12: main (0x555e89f0ed48)\n  13: __libc_start_main (0x7ffab39e8830)\n  14: _start (0x555e89eb7b09)\n  15: <unknown> (0x0)"},"encoding":{"Err":"ErrorMessage { msg: \"expected success, got exit code: 101\\n\\nstderr=error: process didn\\'t exit successfully: `/home/alex/code/rustc-perf/target/release/rustc-fake -vV` (exit code: 101)\\n--- stderr\\nthread \\'main\\' panicked at \\'failed to exec: No such file or directory (os error 2)\\', collector/src/bin/rustc-fake.rs:239:5\\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.\\n\\n\\n\\n stdout=\" }\n\nstack backtrace:\n   0: failure::backtrace::internal::InternalBacktrace::new::h283f8a35e18b39ba (0x555e8a3293c8)\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/internal.rs:44\n   1: failure::backtrace::Backtrace::new::h5621ac89965a2646 (0x555e8a329580)\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/mod.rs:111\n      <failure::backtrace::Backtrace as core::default::Default>::default::h8dabef315f83383d\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/mod.rs:125\n   2: <failure::error::error_impl::ErrorImpl as core::convert::From<F>>::from::heb5b6ca482359042 (0x555e8a2b1b93)\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error/error_impl.rs:19\n      <failure::error::Error as core::convert::From<F>>::from::hfc86b78db702192c\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error/mod.rs:36\n      failure::error_message::err_msg::h461cd386e782dee1\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error_message.rs:12\n      collector::command_output::hc1885b57ce0596d9\n             at collector/src/lib.rs:658\n   3: collector::execute::CargoProcess::run_rustc::h065da9d19ac8b57b (0x555e89f1112b)\n             at collector/src/bin/rustc-perf-collector/execute.rs:230\n   4: collector::execute::Benchmark::measure::haf66a21e925b39f7 (0x555e89f19832)\n             at collector/src/bin/rustc-perf-collector/execute.rs:765\n   5: collector::bench_commit::h4d92175941328511 (0x555e89f04ef3)\n             at collector/src/bin/rustc-perf-collector/main.rs:306\n   6: collector::bench_published::hd09f56af8a9672f1 (0x555e89f0c530)\n             at collector/src/bin/rustc-perf-collector/main.rs:227\n      collector::main_result::h6b0f033b291eba88\n             at collector/src/bin/rustc-perf-collector/main.rs:537\n   7: collector::main::h6fdc93a16be00aad (0x555e89f056ef)\n             at collector/src/bin/rustc-perf-collector/main.rs:382\n   8: std::rt::lang_start::{{closure}}::h80c0acaed3088f8e (0x555e89edb5c3)\n             at /rustc/890881f8f4c77e8670d4b32104c0325fcfefc90f/src/libstd/rt.rs:64\n   9: std::rt::lang_start_internal::{{closure}}::h206ab7e4498aa1c0 (0x555e8a354b53)\n             at src/libstd/rt.rs:49\n      std::panicking::try::do_call::h89a9b41ab5b49bd7\n             at src/libstd/panicking.rs:296\n  10: __rust_maybe_catch_panic (0x555e8a35f08a)\n             at src/libpanic_unwind/lib.rs:82\n  11: std::panicking::try::h1a76c542b7a68f0e (0x555e8a35571d)\n             at src/libstd/panicking.rs:275\n      std::panic::catch_unwind::hbf51b086a93263a6\n             at src/libstd/panic.rs:394\n      std::rt::lang_start_internal::hdbf5055a9a60353b\n             at src/libstd/rt.rs:48\n  12: main (0x555e89f0ed48)\n  13: __libc_start_main (0x7ffab39e8830)\n  14: _start (0x555e89eb7b09)\n  15: <unknown> (0x0)"},"futures":{"Err":"ErrorMessage { msg: \"expected success, got exit code: 101\\n\\nstderr=warning: package replacement is not used: https://github.com/rust-lang/crates.io-index#openssl:0.7.14\\nerror: process didn\\'t exit successfully: `/home/alex/code/rustc-perf/target/release/rustc-fake -vV` (exit code: 101)\\n--- stderr\\nthread \\'main\\' panicked at \\'failed to exec: No such file or directory (os error 2)\\', collector/src/bin/rustc-fake.rs:239:5\\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.\\n\\n\\n\\n stdout=\" }\n\nstack backtrace:\n   0: failure::backtrace::internal::InternalBacktrace::new::h283f8a35e18b39ba (0x555e8a3293c8)\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/internal.rs:44\n   1: failure::backtrace::Backtrace::new::h5621ac89965a2646 (0x555e8a329580)\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/mod.rs:111\n      <failure::backtrace::Backtrace as core::default::Default>::default::h8dabef315f83383d\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/mod.rs:125\n   2: <failure::error::error_impl::ErrorImpl as core::convert::From<F>>::from::heb5b6ca482359042 (0x555e8a2b1b93)\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error/error_impl.rs:19\n      <failure::error::Error as core::convert::From<F>>::from::hfc86b78db702192c\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error/mod.rs:36\n      failure::error_message::err_msg::h461cd386e782dee1\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error_message.rs:12\n      collector::command_output::hc1885b57ce0596d9\n             at collector/src/lib.rs:658\n   3: collector::execute::CargoProcess::run_rustc::h065da9d19ac8b57b (0x555e89f1112b)\n             at collector/src/bin/rustc-perf-collector/execute.rs:230\n   4: collector::execute::Benchmark::measure::haf66a21e925b39f7 (0x555e89f19832)\n             at collector/src/bin/rustc-perf-collector/execute.rs:765\n   5: collector::bench_commit::h4d92175941328511 (0x555e89f04ef3)\n             at collector/src/bin/rustc-perf-collector/main.rs:306\n   6: collector::bench_published::hd09f56af8a9672f1 (0x555e89f0c530)\n             at collector/src/bin/rustc-perf-collector/main.rs:227\n      collector::main_result::h6b0f033b291eba88\n             at collector/src/bin/rustc-perf-collector/main.rs:537\n   7: collector::main::h6fdc93a16be00aad (0x555e89f056ef)\n             at collector/src/bin/rustc-perf-collector/main.rs:382\n   8: std::rt::lang_start::{{closure}}::h80c0acaed3088f8e (0x555e89edb5c3)\n             at /rustc/890881f8f4c77e8670d4b32104c0325fcfefc90f/src/libstd/rt.rs:64\n   9: std::rt::lang_start_internal::{{closure}}::h206ab7e4498aa1c0 (0x555e8a354b53)\n             at src/libstd/rt.rs:49\n      std::panicking::try::do_call::h89a9b41ab5b49bd7\n             at src/libstd/panicking.rs:296\n  10: __rust_maybe_catch_panic (0x555e8a35f08a)\n             at src/libpanic_unwind/lib.rs:82\n  11: std::panicking::try::h1a76c542b7a68f0e (0x555e8a35571d)\n             at src/libstd/panicking.rs:275\n      std::panic::catch_unwind::hbf51b086a93263a6\n             at src/libstd/panic.rs:394\n      std::rt::lang_start_internal::hdbf5055a9a60353b\n             at src/libstd/rt.rs:48\n  12: main (0x555e89f0ed48)\n  13: __libc_start_main (0x7ffab39e8830)\n  14: _start (0x555e89eb7b09)\n  15: <unknown> (0x0)"},"html5ever":{"Err":"ErrorMessage { msg: \"expected success, got exit code: 101\\n\\nstderr=error: process didn\\'t exit successfully: `/home/alex/code/rustc-perf/target/release/rustc-fake -vV` (exit code: 101)\\n--- stderr\\nthread \\'main\\' panicked at \\'failed to exec: No such file or directory (os error 2)\\', collector/src/bin/rustc-fake.rs:239:5\\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.\\n\\n\\n\\n stdout=\" }\n\nstack backtrace:\n   0: failure::backtrace::internal::InternalBacktrace::new::h283f8a35e18b39ba (0x555e8a3293c8)\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/internal.rs:44\n   1: failure::backtrace::Backtrace::new::h5621ac89965a2646 (0x555e8a329580)\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/mod.rs:111\n      <failure::backtrace::Backtrace as core::default::Default>::default::h8dabef315f83383d\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/mod.rs:125\n   2: <failure::error::error_impl::ErrorImpl as core::convert::From<F>>::from::heb5b6ca482359042 (0x555e8a2b1b93)\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error/error_impl.rs:19\n      <failure::error::Error as core::convert::From<F>>::from::hfc86b78db702192c\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error/mod.rs:36\n      failure::error_message::err_msg::h461cd386e782dee1\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error_message.rs:12\n      collector::command_output::hc1885b57ce0596d9\n             at collector/src/lib.rs:658\n   3: collector::execute::CargoProcess::run_rustc::h065da9d19ac8b57b (0x555e89f1112b)\n             at collector/src/bin/rustc-perf-collector/execute.rs:230\n   4: collector::execute::Benchmark::measure::haf66a21e925b39f7 (0x555e89f19832)\n             at collector/src/bin/rustc-perf-collector/execute.rs:765\n   5: collector::bench_commit::h4d92175941328511 (0x555e89f04ef3)\n             at collector/src/bin/rustc-perf-collector/main.rs:306\n   6: collector::bench_published::hd09f56af8a9672f1 (0x555e89f0c530)\n             at collector/src/bin/rustc-perf-collector/main.rs:227\n      collector::main_result::h6b0f033b291eba88\n             at collector/src/bin/rustc-perf-collector/main.rs:537\n   7: collector::main::h6fdc93a16be00aad (0x555e89f056ef)\n             at collector/src/bin/rustc-perf-collector/main.rs:382\n   8: std::rt::lang_start::{{closure}}::h80c0acaed3088f8e (0x555e89edb5c3)\n             at /rustc/890881f8f4c77e8670d4b32104c0325fcfefc90f/src/libstd/rt.rs:64\n   9: std::rt::lang_start_internal::{{closure}}::h206ab7e4498aa1c0 (0x555e8a354b53)\n             at src/libstd/rt.rs:49\n      std::panicking::try::do_call::h89a9b41ab5b49bd7\n             at src/libstd/panicking.rs:296\n  10: __rust_maybe_catch_panic (0x555e8a35f08a)\n             at src/libpanic_unwind/lib.rs:82\n  11: std::panicking::try::h1a76c542b7a68f0e (0x555e8a35571d)\n             at src/libstd/panicking.rs:275\n      std::panic::catch_unwind::hbf51b086a93263a6\n             at src/libstd/panic.rs:394\n      std::rt::lang_start_internal::hdbf5055a9a60353b\n             at src/libstd/rt.rs:48\n  12: main (0x555e89f0ed48)\n  13: __libc_start_main (0x7ffab39e8830)\n  14: _start (0x555e89eb7b09)\n  15: <unknown> (0x0)"},"inflate":{"Err":"ErrorMessage { msg: \"expected success, got exit code: 101\\n\\nstderr=error: process didn\\'t exit successfully: `/home/alex/code/rustc-perf/target/release/rustc-fake -vV` (exit code: 101)\\n--- stderr\\nthread \\'main\\' panicked at \\'failed to exec: No such file or directory (os error 2)\\', collector/src/bin/rustc-fake.rs:239:5\\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.\\n\\n\\n\\n stdout=\" }\n\nstack backtrace:\n   0: failure::backtrace::internal::InternalBacktrace::new::h283f8a35e18b39ba (0x555e8a3293c8)\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/internal.rs:44\n   1: failure::backtrace::Backtrace::new::h5621ac89965a2646 (0x555e8a329580)\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/mod.rs:111\n      <failure::backtrace::Backtrace as core::default::Default>::default::h8dabef315f83383d\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/mod.rs:125\n   2: <failure::error::error_impl::ErrorImpl as core::convert::From<F>>::from::heb5b6ca482359042 (0x555e8a2b1b93)\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error/error_impl.rs:19\n      <failure::error::Error as core::convert::From<F>>::from::hfc86b78db702192c\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error/mod.rs:36\n      failure::error_message::err_msg::h461cd386e782dee1\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error_message.rs:12\n      collector::command_output::hc1885b57ce0596d9\n             at collector/src/lib.rs:658\n   3: collector::execute::CargoProcess::run_rustc::h065da9d19ac8b57b (0x555e89f1112b)\n             at collector/src/bin/rustc-perf-collector/execute.rs:230\n   4: collector::execute::Benchmark::measure::haf66a21e925b39f7 (0x555e89f19832)\n             at collector/src/bin/rustc-perf-collector/execute.rs:765\n   5: collector::bench_commit::h4d92175941328511 (0x555e89f04ef3)\n             at collector/src/bin/rustc-perf-collector/main.rs:306\n   6: collector::bench_published::hd09f56af8a9672f1 (0x555e89f0c530)\n             at collector/src/bin/rustc-perf-collector/main.rs:227\n      collector::main_result::h6b0f033b291eba88\n             at collector/src/bin/rustc-perf-collector/main.rs:537\n   7: collector::main::h6fdc93a16be00aad (0x555e89f056ef)\n             at collector/src/bin/rustc-perf-collector/main.rs:382\n   8: std::rt::lang_start::{{closure}}::h80c0acaed3088f8e (0x555e89edb5c3)\n             at /rustc/890881f8f4c77e8670d4b32104c0325fcfefc90f/src/libstd/rt.rs:64\n   9: std::rt::lang_start_internal::{{closure}}::h206ab7e4498aa1c0 (0x555e8a354b53)\n             at src/libstd/rt.rs:49\n      std::panicking::try::do_call::h89a9b41ab5b49bd7\n             at src/libstd/panicking.rs:296\n  10: __rust_maybe_catch_panic (0x555e8a35f08a)\n             at src/libpanic_unwind/lib.rs:82\n  11: std::panicking::try::h1a76c542b7a68f0e (0x555e8a35571d)\n             at src/libstd/panicking.rs:275\n      std::panic::catch_unwind::hbf51b086a93263a6\n             at src/libstd/panic.rs:394\n      std::rt::lang_start_internal::hdbf5055a9a60353b\n             at src/libstd/rt.rs:48\n  12: main (0x555e89f0ed48)\n  13: __libc_start_main (0x7ffab39e8830)\n  14: _start (0x555e89eb7b09)\n  15: <unknown> (0x0)"},"piston-image":{"Err":"ErrorMessage { msg: \"expected success, got exit code: 101\\n\\nstderr=error: process didn\\'t exit successfully: `/home/alex/code/rustc-perf/target/release/rustc-fake -vV` (exit code: 101)\\n--- stderr\\nthread \\'main\\' panicked at \\'failed to exec: No such file or directory (os error 2)\\', collector/src/bin/rustc-fake.rs:239:5\\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.\\n\\n\\n\\n stdout=\" }\n\nstack backtrace:\n   0: failure::backtrace::internal::InternalBacktrace::new::h283f8a35e18b39ba (0x555e8a3293c8)\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/internal.rs:44\n   1: failure::backtrace::Backtrace::new::h5621ac89965a2646 (0x555e8a329580)\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/mod.rs:111\n      <failure::backtrace::Backtrace as core::default::Default>::default::h8dabef315f83383d\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/mod.rs:125\n   2: <failure::error::error_impl::ErrorImpl as core::convert::From<F>>::from::heb5b6ca482359042 (0x555e8a2b1b93)\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error/error_impl.rs:19\n      <failure::error::Error as core::convert::From<F>>::from::hfc86b78db702192c\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error/mod.rs:36\n      failure::error_message::err_msg::h461cd386e782dee1\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error_message.rs:12\n      collector::command_output::hc1885b57ce0596d9\n             at collector/src/lib.rs:658\n   3: collector::execute::CargoProcess::run_rustc::h065da9d19ac8b57b (0x555e89f1112b)\n             at collector/src/bin/rustc-perf-collector/execute.rs:230\n   4: collector::execute::Benchmark::measure::haf66a21e925b39f7 (0x555e89f19832)\n             at collector/src/bin/rustc-perf-collector/execute.rs:765\n   5: collector::bench_commit::h4d92175941328511 (0x555e89f04ef3)\n             at collector/src/bin/rustc-perf-collector/main.rs:306\n   6: collector::bench_published::hd09f56af8a9672f1 (0x555e89f0c530)\n             at collector/src/bin/rustc-perf-collector/main.rs:227\n      collector::main_result::h6b0f033b291eba88\n             at collector/src/bin/rustc-perf-collector/main.rs:537\n   7: collector::main::h6fdc93a16be00aad (0x555e89f056ef)\n             at collector/src/bin/rustc-perf-collector/main.rs:382\n   8: std::rt::lang_start::{{closure}}::h80c0acaed3088f8e (0x555e89edb5c3)\n             at /rustc/890881f8f4c77e8670d4b32104c0325fcfefc90f/src/libstd/rt.rs:64\n   9: std::rt::lang_start_internal::{{closure}}::h206ab7e4498aa1c0 (0x555e8a354b53)\n             at src/libstd/rt.rs:49\n      std::panicking::try::do_call::h89a9b41ab5b49bd7\n             at src/libstd/panicking.rs:296\n  10: __rust_maybe_catch_panic (0x555e8a35f08a)\n             at src/libpanic_unwind/lib.rs:82\n  11: std::panicking::try::h1a76c542b7a68f0e (0x555e8a35571d)\n             at src/libstd/panicking.rs:275\n      std::panic::catch_unwind::hbf51b086a93263a6\n             at src/libstd/panic.rs:394\n      std::rt::lang_start_internal::hdbf5055a9a60353b\n             at src/libstd/rt.rs:48\n  12: main (0x555e89f0ed48)\n  13: __libc_start_main (0x7ffab39e8830)\n  14: _start (0x555e89eb7b09)\n  15: <unknown> (0x0)"},"regex":{"Err":"ErrorMessage { msg: \"expected success, got exit code: 101\\n\\nstderr=error: process didn\\'t exit successfully: `/home/alex/code/rustc-perf/target/release/rustc-fake -vV` (exit code: 101)\\n--- stderr\\nthread \\'main\\' panicked at \\'failed to exec: No such file or directory (os error 2)\\', collector/src/bin/rustc-fake.rs:239:5\\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.\\n\\n\\n\\n stdout=\" }\n\nstack backtrace:\n   0: failure::backtrace::internal::InternalBacktrace::new::h283f8a35e18b39ba (0x555e8a3293c8)\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/internal.rs:44\n   1: failure::backtrace::Backtrace::new::h5621ac89965a2646 (0x555e8a329580)\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/mod.rs:111\n      <failure::backtrace::Backtrace as core::default::Default>::default::h8dabef315f83383d\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/mod.rs:125\n   2: <failure::error::error_impl::ErrorImpl as core::convert::From<F>>::from::heb5b6ca482359042 (0x555e8a2b1b93)\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error/error_impl.rs:19\n      <failure::error::Error as core::convert::From<F>>::from::hfc86b78db702192c\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error/mod.rs:36\n      failure::error_message::err_msg::h461cd386e782dee1\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error_message.rs:12\n      collector::command_output::hc1885b57ce0596d9\n             at collector/src/lib.rs:658\n   3: collector::execute::CargoProcess::run_rustc::h065da9d19ac8b57b (0x555e89f1112b)\n             at collector/src/bin/rustc-perf-collector/execute.rs:230\n   4: collector::execute::Benchmark::measure::haf66a21e925b39f7 (0x555e89f19832)\n             at collector/src/bin/rustc-perf-collector/execute.rs:765\n   5: collector::bench_commit::h4d92175941328511 (0x555e89f04ef3)\n             at collector/src/bin/rustc-perf-collector/main.rs:306\n   6: collector::bench_published::hd09f56af8a9672f1 (0x555e89f0c530)\n             at collector/src/bin/rustc-perf-collector/main.rs:227\n      collector::main_result::h6b0f033b291eba88\n             at collector/src/bin/rustc-perf-collector/main.rs:537\n   7: collector::main::h6fdc93a16be00aad (0x555e89f056ef)\n             at collector/src/bin/rustc-perf-collector/main.rs:382\n   8: std::rt::lang_start::{{closure}}::h80c0acaed3088f8e (0x555e89edb5c3)\n             at /rustc/890881f8f4c77e8670d4b32104c0325fcfefc90f/src/libstd/rt.rs:64\n   9: std::rt::lang_start_internal::{{closure}}::h206ab7e4498aa1c0 (0x555e8a354b53)\n             at src/libstd/rt.rs:49\n      std::panicking::try::do_call::h89a9b41ab5b49bd7\n             at src/libstd/panicking.rs:296\n  10: __rust_maybe_catch_panic (0x555e8a35f08a)\n             at src/libpanic_unwind/lib.rs:82\n  11: std::panicking::try::h1a76c542b7a68f0e (0x555e8a35571d)\n             at src/libstd/panicking.rs:275\n      std::panic::catch_unwind::hbf51b086a93263a6\n             at src/libstd/panic.rs:394\n      std::rt::lang_start_internal::hdbf5055a9a60353b\n             at src/libstd/rt.rs:48\n  12: main (0x555e89f0ed48)\n  13: __libc_start_main (0x7ffab39e8830)\n  14: _start (0x555e89eb7b09)\n  15: <unknown> (0x0)"},"sentry-cli":{"Err":"ErrorMessage { msg: \"expected success, got exit code: 101\\n\\nstderr=error: process didn\\'t exit successfully: `/home/alex/code/rustc-perf/target/release/rustc-fake -vV` (exit code: 101)\\n--- stderr\\nthread \\'main\\' panicked at \\'failed to exec: No such file or directory (os error 2)\\', collector/src/bin/rustc-fake.rs:239:5\\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.\\n\\n\\n\\n stdout=\" }\n\nstack backtrace:\n   0: failure::backtrace::internal::InternalBacktrace::new::h283f8a35e18b39ba (0x555e8a3293c8)\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/internal.rs:44\n   1: failure::backtrace::Backtrace::new::h5621ac89965a2646 (0x555e8a329580)\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/mod.rs:111\n      <failure::backtrace::Backtrace as core::default::Default>::default::h8dabef315f83383d\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/mod.rs:125\n   2: <failure::error::error_impl::ErrorImpl as core::convert::From<F>>::from::heb5b6ca482359042 (0x555e8a2b1b93)\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error/error_impl.rs:19\n      <failure::error::Error as core::convert::From<F>>::from::hfc86b78db702192c\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error/mod.rs:36\n      failure::error_message::err_msg::h461cd386e782dee1\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error_message.rs:12\n      collector::command_output::hc1885b57ce0596d9\n             at collector/src/lib.rs:658\n   3: collector::execute::CargoProcess::run_rustc::h065da9d19ac8b57b (0x555e89f1112b)\n             at collector/src/bin/rustc-perf-collector/execute.rs:230\n   4: collector::execute::Benchmark::measure::haf66a21e925b39f7 (0x555e89f19832)\n             at collector/src/bin/rustc-perf-collector/execute.rs:765\n   5: collector::bench_commit::h4d92175941328511 (0x555e89f04ef3)\n             at collector/src/bin/rustc-perf-collector/main.rs:306\n   6: collector::bench_published::hd09f56af8a9672f1 (0x555e89f0c530)\n             at collector/src/bin/rustc-perf-collector/main.rs:227\n      collector::main_result::h6b0f033b291eba88\n             at collector/src/bin/rustc-perf-collector/main.rs:537\n   7: collector::main::h6fdc93a16be00aad (0x555e89f056ef)\n             at collector/src/bin/rustc-perf-collector/main.rs:382\n   8: std::rt::lang_start::{{closure}}::h80c0acaed3088f8e (0x555e89edb5c3)\n             at /rustc/890881f8f4c77e8670d4b32104c0325fcfefc90f/src/libstd/rt.rs:64\n   9: std::rt::lang_start_internal::{{closure}}::h206ab7e4498aa1c0 (0x555e8a354b53)\n             at src/libstd/rt.rs:49\n      std::panicking::try::do_call::h89a9b41ab5b49bd7\n             at src/libstd/panicking.rs:296\n  10: __rust_maybe_catch_panic (0x555e8a35f08a)\n             at src/libpanic_unwind/lib.rs:82\n  11: std::panicking::try::h1a76c542b7a68f0e (0x555e8a35571d)\n             at src/libstd/panicking.rs:275\n      std::panic::catch_unwind::hbf51b086a93263a6\n             at src/libstd/panic.rs:394\n      std::rt::lang_start_internal::hdbf5055a9a60353b\n             at src/libstd/rt.rs:48\n  12: main (0x555e89f0ed48)\n  13: __libc_start_main (0x7ffab39e8830)\n  14: _start (0x555e89eb7b09)\n  15: <unknown> (0x0)"},"style-servo":{"Err":"ErrorMessage { msg: \"expected success, got exit code: 101\\n\\nstderr=error: process didn\\'t exit successfully: `/home/alex/code/rustc-perf/target/release/rustc-fake -vV` (exit code: 101)\\n--- stderr\\nthread \\'main\\' panicked at \\'failed to exec: No such file or directory (os error 2)\\', collector/src/bin/rustc-fake.rs:239:5\\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.\\n\\n\\n\\n stdout=\" }\n\nstack backtrace:\n   0: failure::backtrace::internal::InternalBacktrace::new::h283f8a35e18b39ba (0x555e8a3293c8)\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/internal.rs:44\n   1: failure::backtrace::Backtrace::new::h5621ac89965a2646 (0x555e8a329580)\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/mod.rs:111\n      <failure::backtrace::Backtrace as core::default::Default>::default::h8dabef315f83383d\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/mod.rs:125\n   2: <failure::error::error_impl::ErrorImpl as core::convert::From<F>>::from::heb5b6ca482359042 (0x555e8a2b1b93)\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error/error_impl.rs:19\n      <failure::error::Error as core::convert::From<F>>::from::hfc86b78db702192c\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error/mod.rs:36\n      failure::error_message::err_msg::h461cd386e782dee1\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error_message.rs:12\n      collector::command_output::hc1885b57ce0596d9\n             at collector/src/lib.rs:658\n   3: collector::execute::CargoProcess::run_rustc::h065da9d19ac8b57b (0x555e89f1112b)\n             at collector/src/bin/rustc-perf-collector/execute.rs:230\n   4: collector::execute::Benchmark::measure::haf66a21e925b39f7 (0x555e89f19832)\n             at collector/src/bin/rustc-perf-collector/execute.rs:765\n   5: collector::bench_commit::h4d92175941328511 (0x555e89f04ef3)\n             at collector/src/bin/rustc-perf-collector/main.rs:306\n   6: collector::bench_published::hd09f56af8a9672f1 (0x555e89f0c530)\n             at collector/src/bin/rustc-perf-collector/main.rs:227\n      collector::main_result::h6b0f033b291eba88\n             at collector/src/bin/rustc-perf-collector/main.rs:537\n   7: collector::main::h6fdc93a16be00aad (0x555e89f056ef)\n             at collector/src/bin/rustc-perf-collector/main.rs:382\n   8: std::rt::lang_start::{{closure}}::h80c0acaed3088f8e (0x555e89edb5c3)\n             at /rustc/890881f8f4c77e8670d4b32104c0325fcfefc90f/src/libstd/rt.rs:64\n   9: std::rt::lang_start_internal::{{closure}}::h206ab7e4498aa1c0 (0x555e8a354b53)\n             at src/libstd/rt.rs:49\n      std::panicking::try::do_call::h89a9b41ab5b49bd7\n             at src/libstd/panicking.rs:296\n  10: __rust_maybe_catch_panic (0x555e8a35f08a)\n             at src/libpanic_unwind/lib.rs:82\n  11: std::panicking::try::h1a76c542b7a68f0e (0x555e8a35571d)\n             at src/libstd/panicking.rs:275\n      std::panic::catch_unwind::hbf51b086a93263a6\n             at src/libstd/panic.rs:394\n      std::rt::lang_start_internal::hdbf5055a9a60353b\n             at src/libstd/rt.rs:48\n  12: main (0x555e89f0ed48)\n  13: __libc_start_main (0x7ffab39e8830)\n  14: _start (0x555e89eb7b09)\n  15: <unknown> (0x0)"},"syn":{"Err":"ErrorMessage { msg: \"expected success, got exit code: 101\\n\\nstderr=error: process didn\\'t exit successfully: `/home/alex/code/rustc-perf/target/release/rustc-fake -vV` (exit code: 101)\\n--- stderr\\nthread \\'main\\' panicked at \\'failed to exec: No such file or directory (os error 2)\\', collector/src/bin/rustc-fake.rs:239:5\\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.\\n\\n\\n\\n stdout=\" }\n\nstack backtrace:\n   0: failure::backtrace::internal::InternalBacktrace::new::h283f8a35e18b39ba (0x555e8a3293c8)\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/internal.rs:44\n   1: failure::backtrace::Backtrace::new::h5621ac89965a2646 (0x555e8a329580)\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/mod.rs:111\n      <failure::backtrace::Backtrace as core::default::Default>::default::h8dabef315f83383d\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/mod.rs:125\n   2: <failure::error::error_impl::ErrorImpl as core::convert::From<F>>::from::heb5b6ca482359042 (0x555e8a2b1b93)\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error/error_impl.rs:19\n      <failure::error::Error as core::convert::From<F>>::from::hfc86b78db702192c\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error/mod.rs:36\n      failure::error_message::err_msg::h461cd386e782dee1\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error_message.rs:12\n      collector::command_output::hc1885b57ce0596d9\n             at collector/src/lib.rs:658\n   3: collector::execute::CargoProcess::run_rustc::h065da9d19ac8b57b (0x555e89f1112b)\n             at collector/src/bin/rustc-perf-collector/execute.rs:230\n   4: collector::execute::Benchmark::measure::haf66a21e925b39f7 (0x555e89f19832)\n             at collector/src/bin/rustc-perf-collector/execute.rs:765\n   5: collector::bench_commit::h4d92175941328511 (0x555e89f04ef3)\n             at collector/src/bin/rustc-perf-collector/main.rs:306\n   6: collector::bench_published::hd09f56af8a9672f1 (0x555e89f0c530)\n             at collector/src/bin/rustc-perf-collector/main.rs:227\n      collector::main_result::h6b0f033b291eba88\n             at collector/src/bin/rustc-perf-collector/main.rs:537\n   7: collector::main::h6fdc93a16be00aad (0x555e89f056ef)\n             at collector/src/bin/rustc-perf-collector/main.rs:382\n   8: std::rt::lang_start::{{closure}}::h80c0acaed3088f8e (0x555e89edb5c3)\n             at /rustc/890881f8f4c77e8670d4b32104c0325fcfefc90f/src/libstd/rt.rs:64\n   9: std::rt::lang_start_internal::{{closure}}::h206ab7e4498aa1c0 (0x555e8a354b53)\n             at src/libstd/rt.rs:49\n      std::panicking::try::do_call::h89a9b41ab5b49bd7\n             at src/libstd/panicking.rs:296\n  10: __rust_maybe_catch_panic (0x555e8a35f08a)\n             at src/libpanic_unwind/lib.rs:82\n  11: std::panicking::try::h1a76c542b7a68f0e (0x555e8a35571d)\n             at src/libstd/panicking.rs:275\n      std::panic::catch_unwind::hbf51b086a93263a6\n             at src/libstd/panic.rs:394\n      std::rt::lang_start_internal::hdbf5055a9a60353b\n             at src/libstd/rt.rs:48\n  12: main (0x555e89f0ed48)\n  13: __libc_start_main (0x7ffab39e8830)\n  14: _start (0x555e89eb7b09)\n  15: <unknown> (0x0)"},"tokio-webpush-simple":{"Err":"ErrorMessage { msg: \"expected success, got exit code: 101\\n\\nstderr=error: process didn\\'t exit successfully: `/home/alex/code/rustc-perf/target/release/rustc-fake -vV` (exit code: 101)\\n--- stderr\\nthread \\'main\\' panicked at \\'failed to exec: No such file or directory (os error 2)\\', collector/src/bin/rustc-fake.rs:239:5\\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.\\n\\n\\n\\n stdout=\" }\n\nstack backtrace:\n   0: failure::backtrace::internal::InternalBacktrace::new::h283f8a35e18b39ba (0x555e8a3293c8)\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/internal.rs:44\n   1: failure::backtrace::Backtrace::new::h5621ac89965a2646 (0x555e8a329580)\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/mod.rs:111\n      <failure::backtrace::Backtrace as core::default::Default>::default::h8dabef315f83383d\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/mod.rs:125\n   2: <failure::error::error_impl::ErrorImpl as core::convert::From<F>>::from::heb5b6ca482359042 (0x555e8a2b1b93)\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error/error_impl.rs:19\n      <failure::error::Error as core::convert::From<F>>::from::hfc86b78db702192c\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error/mod.rs:36\n      failure::error_message::err_msg::h461cd386e782dee1\n             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error_message.rs:12\n      collector::command_output::hc1885b57ce0596d9\n             at collector/src/lib.rs:658\n   3: collector::execute::CargoProcess::run_rustc::h065da9d19ac8b57b (0x555e89f1112b)\n             at collector/src/bin/rustc-perf-collector/execute.rs:230\n   4: collector::execute::Benchmark::measure::haf66a21e925b39f7 (0x555e89f19832)\n             at collector/src/bin/rustc-perf-collector/execute.rs:765\n   5: collector::bench_commit::h4d92175941328511 (0x555e89f04ef3)\n             at collector/src/bin/rustc-perf-collector/main.rs:306\n   6: collector::bench_published::hd09f56af8a9672f1 (0x555e89f0c530)\n             at collector/src/bin/rustc-perf-collector/main.rs:227\n      collector::main_result::h6b0f033b291eba88\n             at collector/src/bin/rustc-perf-collector/main.rs:537\n   7: collector::main::h6fdc93a16be00aad (0x555e89f056ef)\n             at collector/src/bin/rustc-perf-collector/main.rs:382\n   8: std::rt::lang_start::{{closure}}::h80c0acaed3088f8e (0x555e89edb5c3)\n             at /rustc/890881f8f4c77e8670d4b32104c0325fcfefc90f/src/libstd/rt.rs:64\n   9: std::rt::lang_start_internal::{{closure}}::h206ab7e4498aa1c0 (0x555e8a354b53)\n             at src/libstd/rt.rs:49\n      std::panicking::try::do_call::h89a9b41ab5b49bd7\n             at src/libstd/panicking.rs:296\n  10: __rust_maybe_catch_panic (0x555e8a35f08a)\n             at src/libpanic_unwind/lib.rs:82\n  11: std::panicking::try::h1a76c542b7a68f0e (0x555e8a35571d)\n             at src/libstd/panicking.rs:275\n      std::panic::catch_unwind::hbf51b086a93263a6\n             at src/libstd/panic.rs:394\n      std::rt::lang_start_internal::hdbf5055a9a60353b\n             at src/libstd/rt.rs:48\n  12: main (0x555e89f0ed48)\n  13: __libc_start_main (0x7ffab39e8830)\n  14: _start (0x555e89eb7b09)\n  15: <unknown> (0x0)"}}}